# Generated by Django 3.2.6 on 2022-10-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0002_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='ligne_bon_commande',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='BC'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='utiliser_ligne_bon_commande',
            field=models.BooleanField(blank=True, default=False, verbose_name='utiliser ligne bon de commande'),
        ),
    ]
