# Generated by Django 3.2.6 on 2022-10-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0003_auto_20221013_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='montant',
            field=models.FloatField(blank=True, default=0, verbose_name='montant de la facture'),
        ),
        migrations.AlterField(
            model_name='facturation',
            name='ligne_bon_commande',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Remplacer vos références'),
        ),
        migrations.AlterField(
            model_name='facturation',
            name='utiliser_ligne_bon_commande',
            field=models.BooleanField(blank=True, default=False, verbose_name='Je voudrais remplacer vos références'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='mode_reglement',
            field=models.CharField(choices=[('Chèque', 'Chèque'), ('Espèce', 'Espèce'), ('Virement', 'Virement')], default='Chèque', max_length=10, verbose_name='mode'),
        ),
    ]
